### PR TITLE
generate installer on CLANG64 environment

### PR DESCRIPTION
**Pull request by MehdiChinoune**

### CODE REVIEW

**Comment by lazka** [comment]
Do you have a plan for Windows 8.1?

**Comment by MehdiChinoune** [comment]
> Do you have a plan for Windows 8.1?

No.

**Comment by lazka** [comment]
What do you think about using clang64, since that is a bit smaller?

**Comment by MehdiChinoune** [comment]
> What do you think about using clang64, since that is a bit smaller?

No problem.

**Pull request merged**
