### PR TITLE
Use github-cli to upload installers

### PR DESCRIPTION
**Pull request by MehdiChinoune**

### CODE REVIEW

**Comment by lazka** [comment]
This will not remove existing assets that contain a date, right? Maybe we should just have the "latest" variants anyway.

**Comment by MehdiChinoune** [comment]
> This will not remove existing assets that contain a date, right? Maybe we should just have the "latest" variants anyway.

Yes, It will just overwrite files with same name.

**Comment by lazka** [comment]
ok, let's give this a try then, thanks!

**Comment by jeremyd2019** [comment]
Out of curiosity, what's the problem with eine/tip?

**Comment by lazka** [comment]
> Out of curiosity, what's the problem with eine/tip?

https://github.com/eine/tip/issues/160

**Pull request merged**
